#sdk: "/Users/lucascampbell-rossen/.rvm/gems/ruby-1.9.2-p290/gems/rhodes-3.3.3"
sdk: "/Users/lucascampbell-rossen/rhomobile/rhodes"
sdkversion: 3.3.3
name: auth_rhodes
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator6.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.authrhodes
  BundleURLScheme: authrhodes
wp:
  productid: '34bb53e0-ee43-012f-c16c-70cd60f27196'
symbian:
  uid: '0xe4cfa056'
android:
  version: 2.1

extensions: ["json", "another-extension"]
